ydlidar_node:
  port: /dev/ttyUSB1
  frame_id: laser_frame1
  ignore_array: ""
  baudrate: 230400
  samp_rate: 9
  resolution_fixed: true
  singleChannel: false
  auto_reconnect: true
  reversion: true
  isToFLidar: false
  angle_max: 180.0
  angle_min: -180.0
  max_range: 16.0
  min_range: 0.01
  frequency: 10.0