#!/usr/bin/env python3

from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription(
        [
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_map",
                arguments=[
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "1",
                    "map",
                    "base_footprint",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_footprint",
                arguments=[
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "1",
                    "base_footprint",
                    "base_link",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_map",
                arguments=[
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "0",
                    "1",
                    "base_link",
                    "laser",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_laser0",
                arguments=[
                    "0.34",
                    "0.09",
                    "0.35",
                    "0.0",
                    "0.0",
                    "0.0",
                    "1.0",
                    "base_link",
                    "laser_frame0",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_laser1",
                arguments=[
                    "0.00",
                    "-0.09",
                    "0.35",
                    "0.0",
                    "1.0",
                    "0.0",
                    "0.0",
                    "base_link",
                    "laser_frame1",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_gimbal",
                arguments=[
                    "0.25",
                    "0.00",
                    "0.54",
                    "0",
                    "0",
                    "0",
                    "1",
                    "base_link",
                    "gimbal_camera_mount",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_camera",
                arguments=[
                    "0.04",
                    "-0.013",
                    "0.0",
                    "0",
                    "0",
                    "0",
                    "1",
                    "gimbal_camera_mount",
                    "camera_base",
                ],
            ),
            Node(
                package="tf2_ros",
                executable="static_transform_publisher",
                name="tf_publisher_zed",
                arguments=[
                    "0.0",
                    "0.0",
                    "0.0",
                    "0",
                    "0",
                    "0",
                    "1",
                    "camera_base",
                    "zed_base_link",
                ],
            ),
        ]
    )
